apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3proxy.fullname" . }}
  labels:
    {{- include "s3proxy.labels" . | nindent 4 }}
type: Opaque
data:
  targetCredential: {{ .Values.azure.storageAccount.accessKey | b64enc | quote }}