apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adaptive.configSecret.fullname" . }}
type: Opaque
data:
  config.toml: |-
    {{ .Files.Get "config.toml" | b64enc }}
  dbUrl: {{ required "A db_url is required!" .Values.secrets.dbUrl | b64enc }}
  cookiesSecret: {{ required "A cookies secret is required!" .Values.secrets.cookiesSecret | b64enc }}
  modelRegistryUrl: {{ required "A modelRegistryUrl is required!" .Values.secrets.modelRegistryUrl | b64enc }}
{{- if .Values.secrets.objectStorageConfig }}
{{- range $key, $value := .Values.secrets.objectStorageConfig }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
  