apiVersion: v1
kind: Service
metadata:
  name: {{ include "adaptive.controlPlane.service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.controlPlane.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "adaptive.controlPlane.selectorLabels" . | nindent 4 }}
  {{- $ports := include "adaptive.controlPlane.ports" . | fromJson }}
  ports:
    - name: {{ $ports.http.name }}
      port: {{ .Values.controlPlane.servicePort | default 80 | int}}
      targetPort: {{ $ports.http.containerPort }}
    - name: {{ $ports.internal.name }}
      port: {{ $ports.internal.containerPort }}
      targetPort: {{ $ports.internal.containerPort }}