apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adaptive.controlPlane.fullname" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.controlPlane.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controlPlane.replicaCount | default 1 | int }}
  selector:
    matchLabels:
      {{- include "adaptive.controlPlane.selectorLabels" . | nindent 6}}      
  template:
    metadata:
      {{- with .Values.controlPlane.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adaptive.labels" . | nindent 8 }}
        {{- include "adaptive.controlPlane.selectorLabels" . | nindent 8 }}
        {{- with .Values.controlPlane.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      nodeSelector:
        {{- with .Values.controlPlane.nodeSelector}}
        {{ toYaml . }}
        {{- end}}
      {{- if .Values.controlPlane.tolerations}}
      tolerations:
        {{- toYaml .Values.controlPlane.tolerations | nindent 8 }}
      {{- end}}
      volumes:
        - name: conf
          secret:
            secretName: {{ include "adaptive.configSecret.fullname" . }}
            items:
              - key: config.toml
                path: config.toml
      {{- $ports := include "adaptive.controlPlane.ports" . | fromJson }}
      containers:
        - name: control-plane
          image: "{{ include "adaptive.controlPlane.imageUri" . }}"
          imagePullPolicy: {{ .Values.controlPlane.image.pullPolicy }}
          ports:
            - containerPort: {{ $ports.http.containerPort }}
          volumeMounts:
            - mountPath: "/etc/kubernetes/conf"
              name: conf
              readOnly: true
          env:
            - name: ADAPTIVE_APP__SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "adaptive.configSecret.fullname" . }}
                  key: cookiesSecret
            - name: ADAPTIVE_CONFIG_FILE
              value: /etc/kubernetes/conf/config.toml
            - name: ADAPTIVE_DB__RUN_MIGRATIONS
              value: {{ .Values.controlPlane.runDbMigrations | default true | quote }}
            - name: ADAPTIVE_DB__URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "adaptive.configSecret.fullname" . }}
                  key: dbUrl
            - name: ADAPTIVE_HARMONY__URL
              value: "http://{{ include "adaptive.harmony.service.fullname" . }}"
            - name: ADAPTIVE_SERVER__BIND
              value: "127.0.0.1:{{ $ports.http.containerPort }}"
            - name: ADAPTIVE_SERVER__ROOT_URL
              value: {{ .Values.controlPlane.rootUrl }}