{{- if and (hasKey .Values "externalSecret") (default false (index .Values.externalSecret "enabled")) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "adaptive.controlPlane.externalSecret.fullname" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "adaptive.externalSecretStore.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "adaptive.controlPlane.configSecret.fullname" . }}
    creationPolicy: Owner
  data:
  - secretKey: dbUrl
    remoteRef:
      {{- with .Values.externalSecret.data.dbUrl.remoteRef }}
      {{- toYaml . | nindent 6}}
      {{- end }}
  - secretKey: cookiesSecret
    remoteRef:
      {{- with .Values.externalSecret.data.cookiesSecret.remoteRef }}
      {{- toYaml . | nindent 6}}
      {{- end }}
  - secretKey: controlPlaneAuthConfig
    remoteRef:
      {{- with .Values.externalSecret.data.controlPlaneAuthConfig.remoteRef }}
      {{- toYaml . | nindent 6}}
      {{- end }}
{{- end }}
