{{- if and (hasKey .Values "externalSecret") (default false (index .Values.externalSecret "enabled")) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "adaptive.harmony.externalSecret.fullname" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "adaptive.externalSecretStore.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "adaptive.harmony.configSecret.fullname" . }}
    creationPolicy: Owner
  data:
  - secretKey: ADAPTIVE_MODEL_REGISTRY
    remoteRef:
      {{- with .Values.externalSecret.data.modelRegistryUrl.remoteRef }}
      {{- toYaml . | nindent 6}}
      {{- end }}
  {{- if .Values.externalSecret.data.objectStorageConfig }}
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      {{- with .Values.externalSecret.data.objectStorageConfig.awsAccessKeyId.remoteRef }}
      {{- toYaml . | nindent 6}}
      {{- end }}
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      {{- with .Values.externalSecret.data.objectStorageConfig.awsSecretAccessKey.remoteRef }}
      {{- toYaml . | nindent 6}}
      {{- end }}
  - secretKey: AWS_ENDPOINT_URL_S3
    remoteRef:
      {{- with .Values.externalSecret.data.objectStorageConfig.awsEndpointUrlS3.remoteRef }}
      {{- toYaml . | nindent 6}}
      {{- end }}
  {{- end }}
{{- end }}