{{- if and (hasKey .Values "externalSecret") (default false (index .Values.externalSecret "enabled")) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "adaptive.controlPlane.secret.fullname" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "adaptive.externalSecretStore.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "adaptive.controlPlane.secret.fullname" . }}
    creationPolicy: Owner
  data:
  - secretKey: dbUrl
    remoteRef:
      {{- with .Values.externalSecret.data.dbUrl.remoteRef }}
      {{- toYaml . | nindent 6}}
      {{- end }}
  - secretKey: cookiesSecret
    remoteRef:
      {{- with .Values.externalSecret.data.cookiesSecret.remoteRef }}
      {{- toYaml . | nindent 6}}
      {{- end }}
  - secretKey: oidc_providers
    remoteRef:
      {{- with .Values.externalSecret.data.oidcProviders.remoteRef }}
      {{- toYaml . | nindent 6}}
      {{- end }}
{{- end }}
