{{- if and (hasKey .Values "externalSecret") (default false (index .Values.externalSecret "enabled")) }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "adaptive.externalSecretStore.fullname" . }}
spec:
  {{- with .Values.externalSecret.spec }}
  {{ toYaml . | nindent 2 }}
  {{- end}}
{{- end}}