{{- if .Values.harmony.inferenceFleet }}
{{- range $pool := .Values.harmony.inferenceFleet }}

{{- $poolMerged := mergeOverwrite $.Values.harmony $pool }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject  # CRD managed by Keda operator
metadata:
  name: {{ include "adaptive.harmony.deployment.fullname" $ }}-{{ $pool.name | snakecase }}
  labels:
    {{- include "adaptive.labels" $ | nindent 4 }}
    {{- include "adaptive.harmony.deployment.selectorLabels" $ | nindent 4 }}
    inference-pool: {{ $pool.name | snakecase }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "adaptive.harmony.deployment.fullname" $ }}-{{ $pool.name | snakecase }}
  pollingInterval:  30                                      # Optional. Default: 30 seconds
  cooldownPeriod:   180                                     # Optional. Default: 300 seconds
  initialCooldownPeriod:  0                                 # Optional. Default: 0 seconds
  minReplicaCount:  {{ $pool.minReplicaCount | default 1 | int }}   # Optional. Default: 1
  maxReplicaCount:  {{ $pool.maxReplicaCount | default 2 | int }}   # Optional. Default: 2
  triggers:
  - type: prometheus
    metadata:
      # prometheus endpoint
      serverAddress: http://adaptive-prometheus
      #  get the percent of timed-out requests
      query: sum(rate(harmony_ttft_timeout_count{pool="{{ $pool.name }}"}[5m])) / clamp_min(sum(rate(harmony_ttft_ms_count{pool="{{ $pool.name }}"}[5m])), 1) * 100
      #  TODO PASS TRESHOLD from values
      threshold: '5.0'
      activationThreshold: '0'
{{- end }}
{{- end }}