{{- if .Values.computePool.training }}
{{- range $pool := .Values.computePool.training }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adaptive.harmony.fullname" $ }}-{{ $pool.name | kebabcase }}-svc
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "adaptive.labels" $ | nindent 4 }}
    {{- include "adaptive.harmony.selectorLabels" $ | nindent 4 }}
    training-pool: {{ $pool.name | kebabcase }}
spec:
  type: ClusterIP
  selector:
    {{- include "adaptive.harmony.selectorLabels" $ | nindent 4}}
    training-pool: {{ $pool.name | kebabcase }}
    apps.kubernetes.io/pod-index: "0"
  ports:
    {{- $ports := include "adaptive.harmony.ports" $ | fromJson }}
    - name: {{ $ports.http.name }}
      port: {{ $ports.http.port }}
      targetPort: {{ $ports.http.containerPort }}
    {{- if $.Values.tensorboard.enabled }}
    - name: {{ $ports.tensorboard.name }}
      port: {{ $ports.tensorboard.containerPort }}
      targetPort: {{ $ports.tensorboard.containerPort }}
    {{- end }}
{{- end }}
{{- end }}