{{- $harmonySettings := include "adaptive.harmony.settings" . | fromJson }}

{{- if .Values.harmony.inferenceFleet }}
{{- range $pool := .Values.harmony.inferenceFleet }}

{{- $poolMerged := mergeOverwrite $.Values.harmony $pool }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adaptive.harmony.deployment.fullname" $ }}-{{ $pool.name | kebabcase }}
  namespace: {{ $.Release.Namespace}}
  labels:
    {{- include "adaptive.labels" $ | nindent 4 }}
    {{- include "adaptive.harmony.deployment.selectorLabels" $ | nindent 4 }}
    inference-pool: {{ $pool.name | kebabcase }}
spec:
  replicas: {{ $pool.minReplicaCount | default 1 | int }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "adaptive.harmony.deployment.selectorLabels" $ | nindent 6}}
      inference-pool: {{ $pool.name | kebabcase }}
  template:
    metadata:
      {{- with $poolMerged.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adaptive.labels" $ | nindent 8 }}
        {{- include "adaptive.harmony.deployment.selectorLabels" $ | nindent 8 }}
        inference-pool: {{ $pool.name | kebabcase }}
        {{- with $pool.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if $.Values.serviceAccount.name }}
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      {{- end }}
      nodeSelector:
        {{- with $poolMerged.nodeSelector }}
        {{ toYaml . }}
        {{- end}}
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      initContainers:
      - name: init-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R  1002:1000 {{ $harmonySettings.working_dir }} {{ $harmonySettings.shared_master_worker_folder }} {{ $harmonySettings.any_path_config.cloud_cache }}']
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: workdir-volume
            mountPath: {{ $harmonySettings.working_dir }}
          - name: cloud-cache-volume
            mountPath: {{ $harmonySettings.any_path_config.cloud_cache }}
      containers:
        - name: harmony
          image: "{{ include "adaptive.harmony.imageUri" $ }}"
          imagePullPolicy: {{ $.Values.harmony.image.pullPolicy }}
          resources:
            limits:
              {{- toYaml $poolMerged.resources.limits | nindent 14 }}
              {{- if $poolMerged.gpusPerReplica}}
              nvidia.com/gpu: {{ $poolMerged.gpusPerReplica }}
              {{- end}}
            requests:
              {{- toYaml $poolMerged.resources.requests | nindent 14 }}
              {{- if $poolMerged.gpusPerReplica }}
              nvidia.com/gpu: {{ $poolMerged.gpusPerReplica }}
              {{- end}}
          ports:
            {{- $ports := include "adaptive.harmony.ports" $ | fromJson }}
            - containerPort: {{ $ports.http.containerPort }}
              name: {{ $ports.http.name }}
            - containerPort: {{ $ports.queue.containerPort }}
              name: {{ $ports.queue.name }}
            - containerPort: {{ $ports.torch.containerPort }}
              name: {{ $ports.torch.name }} 
          envFrom:
            - secretRef:
                name: {{ include "adaptive.harmony.configSecret.fullname" $ }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGE_TAG
              value: {{ $.Values.harmony.image.tag | quote }}
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ORDINAL
              value: "0"
            - name: GPU_COUNT
              value: "{{ $poolMerged.gpusPerReplica | default 1 }}"
            - name: WORLD_SIZE
              value: "{{ $poolMerged.gpusPerReplica | default 1 }}"
            - name: MASTER_ADDR
              value: "127.0.0.1"
            - name: MASTER_PORT
              value: "{{ $ports.torch.containerPort }}"
            - name: QUEUE_PORT
              value: "{{ $ports.queue.containerPort }}"
            - name: CONTROL_PLANE_URL
              value: "http://{{ include "adaptive.controlPlane.service.fullname" $ }}"
            - name: GROUP
              value: {{ $pool.name }}
            - name: GROUP_CAPABILITIES
              value: "INFERENCE"
            - name: PARTITION_KEY
              value: "$(MY_POD_NAME)"
            - name: SERVICE_URL
              value: "http://$(MY_POD_IP):{{ $ports.http.containerPort }}"
            - name: ADAPTIVE_LOGGING_LEVEL
              value: info
            - name: ADAPTIVE_MODE
              value: PROD
            {{- if $poolMerged.extraEnvVars }}
            {{- range $key, $value := $poolMerged.extraEnvVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: workdir-volume
              mountPath: {{ $harmonySettings.working_dir }}
            - name: cloud-cache-volume
              mountPath: {{ $harmonySettings.any_path_config.cloud_cache }}
            - name: harmony-settings-volume
              mountPath: /opt/adaptive/harmony_settings/docker.json
              subPath: docker.json
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: cloud-cache-volume
          emptyDir: {}
        - name: workdir-volume
          emptyDir: {}
        - name: harmony-settings-volume
          configMap:
            name: {{ include "adaptive.harmony.settingsConfigMap.fullname" $ }}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi

{{- end }}
{{- end }}