apiVersion: v1
kind: Service
metadata:
  name: {{ include "adaptive.harmony.service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.harmony.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: "{{ include "adaptive.harmony.fullname" . }}-0"
  ports:
    {{- $ports := include "adaptive.harmony.ports" . | fromJson }}
    - name: {{ $ports.http.name }}
      port: {{ $ports.http.port }}
      targetPort: {{ $ports.http.containerPort }}
    {{- if .Values.tensorboard.enabled }}
    - name: {{ $ports.tensorboard.name }}
      port: {{ $ports.tensorboard.containerPort }}
      targetPort: {{ $ports.tensorboard.containerPort }}
    {{- end }}