{{- if .Values.installPostgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adaptive.postgresql.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.postgresql.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "adaptive.postgresql.password" . | b64enc }}
{{- end }}

