{{- if .Values.lgtm.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adaptive.lgtm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.lgtm.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "adaptive.lgtm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adaptive.lgtm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: lgtm
          image: "{{ .Values.lgtm.image.repository }}:{{ .Values.lgtm.image.tag }}"
          imagePullPolicy: {{ .Values.lgtm.image.pullPolicy }}
          {{- with .Values.lgtm.env }}
          env:
            {{- range $name, $value := . }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: 3000
            - containerPort: 4040
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 9090
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/ready
          {{- with .Values.lgtm.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
      {{- with .Values.lgtm.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lgtm.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          {{- if .Values.lgtm.persistence.enabled }}
          {{- $type := .Values.lgtm.persistence.type | default "pvc" }}
          {{- if eq $type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ include "adaptive.lgtm.pvc.fullname" . }}
          {{- else if eq $type "hostPath" }}
          hostPath:
            path: {{ .Values.lgtm.persistence.hostPath }}
            type: DirectoryOrCreate
          {{- else if eq $type "memory" }}
          emptyDir:
            medium: Memory
          {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
