apiVersion: v1
kind: ConfigMap
metadata:
  name: harmony-gang-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
data:
  {{- if .Values.containerRegistry }}
  HARMONY_IMAGE_REPO: "{{ .Values.containerRegistry }}/{{ .Values.harmony.image.repository }}"
  RECIPE_RUNNER_IMAGE_REPO: "{{ .Values.containerRegistry }}/{{ .Values.sandkasten.recipeRunner.repository }}"
  {{- else }}
  HARMONY_IMAGE_REPO: {{ .Values.harmony.image.repository | quote }}
  RECIPE_RUNNER_IMAGE_REPO: {{ .Values.sandkasten.recipeRunner.repository | quote }}
  {{- end }}
  COMMON_ENV_CONFIGMAP: "harmony-common-env"
  RECIPE_RUNNER_ENV_CONFIGMAP: "recipe-runner-env"
  # Harmony pod resources (CPU/memory requests and limits for gang-spawned pods)
  CPU_REQUESTS: {{ .Values.adaptiveOperator.resources.requests.cpu | quote }}
  MEMORY_REQUESTS_MB: {{ .Values.adaptiveOperator.resources.requests.memoryMB | quote }}
  CPU_LIMITS: {{ .Values.adaptiveOperator.resources.limits.cpu | quote }}
  MEMORY_LIMITS_MB: {{ .Values.adaptiveOperator.resources.limits.memoryMB | quote }}
  {{- if .Values.adaptiveOperator.customLabels }}
  CUSTOM_LABELS: {{ .Values.adaptiveOperator.customLabels | toJson | quote }}
  {{- end }}
  {{- if .Values.adaptiveOperator.customAnnotations }}
  CUSTOM_ANNOTATIONS: {{ .Values.adaptiveOperator.customAnnotations | toJson | quote }}
  {{- end }}
  {{- if .Values.adaptiveOperator.extraResources }}
  EXTRA_RESOURCES: {{ .Values.adaptiveOperator.extraResources | quote }}
  {{- end }}
  {{- with (first .Values.imagePullSecrets) }}
  IMAGE_PULL_SECRET: {{ .name | quote }}
  {{- end }}
  DELETE_FAILED_JOBS: {{ .Values.adaptiveOperator.deleteFailedJobs | quote }}
  CONTROL_PLANE_URL: {{ include "adaptive.controlPlane.privateHttpEndpoint" . | quote }}
  {{- if .Values.adaptiveOperator.harmonyImageTagsWhitelist }}
  HARMONY_IMAGE_TAGS_WHITELIST: {{ .Values.adaptiveOperator.harmonyImageTagsWhitelist | quote }}
  {{- end }}
  SERVICE_ACCOUNT_NAME: {{ include "adaptive.harmony.serviceAccount.fullname" . | quote }}
  {{- if .Values.adaptiveOperator.extraVolumes }}
  EXTRA_VOLUMES: {{ .Values.adaptiveOperator.extraVolumes | quote }}
  {{- end }}
