apiVersion: v1
kind: ConfigMap
metadata:
  name: recipe-runner-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
data:
  CONTROL_PLANE_URL: {{ include "adaptive.controlPlane.publicHttpEndpoint" . | quote }}
  {{- range $key, $value := .Values.adaptiveOperator.extraRecipeRunnerEnvVars }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
