apiVersion: v1
kind: Service
metadata:
  name: {{ include "adaptive.redis.service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.redis.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "adaptive.redis.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}