name: adaptive
description: Helm Chart for Adaptive Engine
kubeVersion: ">=1.26.0-0"
type: application
version: 0.0.4
apiVersion: v2
appVersion: "1.0"
maintainers:
  - name: adaptive-ml
    url: https://www.adaptive-ml.com/
