{
 "title": "Control plane KPIs (http/database/interactions)",
 "description": "HTTP Metric based Otel metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(up{app_kubernetes_io_component=\"control-plane\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(concorde_http_server_request_duration_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate (Non 5xx)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(concorde_http_server_request_duration_seconds_count{http_response_status_code!~\"5..\"}[$__range])) * 100) / sum(rate(concorde_http_server_request_duration_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(concorde_http_server_request_duration_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(concorde_http_server_request_duration_seconds_count{http_response_status_code=~\"4..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(concorde_http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(concorde_http_server_request_duration_seconds_count{http_response_status_code=~\"2..|3..\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(concorde_http_server_request_duration_seconds_count{http_response_status_code=~\"4..\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(concorde_http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50/P90/P99 Request Duration Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(concorde_http_server_request_duration_seconds_bucket[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(concorde_http_server_request_duration_seconds_bucket[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(concorde_http_server_request_duration_seconds_bucket[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Request Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_route, graphql_operation) (increase(concorde_http_server_request_duration_seconds_count[$__range]))",
     "legendFormat": "{{http_route}} {{graphql_operation}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(http_route, graphql_operation) (rate(concorde_http_server_request_duration_seconds_sum[$__range]))) / (sum by(http_route, graphql_operation) (rate(concorde_http_server_request_duration_seconds_count[$__range])) > 0)",
     "legendFormat": "{{graphql_operation}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Requests Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Workload",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by(http_route) (rate(concorde_http_server_request_duration_seconds_count[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by(http_route) (rate(concorde_http_server_request_duration_seconds_count{http_response_status_code!~\"5..\"}[$__range])) * 100) / sum by(http_route) (rate(concorde_http_server_request_duration_seconds_count[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(http_route, le) (rate(concorde_http_server_request_duration_seconds_bucket[$__range])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(http_route, le) (rate(concorde_http_server_request_duration_seconds_bucket[$__range])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(http_route, le) (rate(concorde_http_server_request_duration_seconds_bucket[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Connections Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(concorde_db_connections_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Failed Connections",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(concorde_db_connections_failed_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 14, "x": 10, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((rate(concorde_db_connections_total[$__range]) - rate(concorde_db_connections_failed_total[$__range])) * 100) / rate(concorde_db_connections_total[$__range])",
       "legendFormat": "{{db_query_type}}"
      }
     ]
    },
    {
     "title": "Connections Repartition",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(db_query_type) (increase(concorde_db_connections_duration_seconds_count[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Connection Duration",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by(db_query_type) (rate(concorde_db_connections_duration_seconds_sum[$__range]))) / (sum by(db_query_type) (rate(concorde_db_connections_duration_seconds_count[$__range])) > 0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Request Rate Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(concorde_token_generated_total[$__range]))",
     "legendFormat": "Generated"
    },
    {
     "expr": "sum(rate(concorde_token_processed_total[$__range]))",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Model Repartition per Processed",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(model) (increase(concorde_token_processed_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Repartition per Generated",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(model) (increase(concorde_token_generated_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}