apiVersion: v1
entries:
  adaptive:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2024-12-13T15:38:03.853058+01:00"
    description: Helm Chart for Adaptive Engine
    digest: 7c524045e3a001cbd5f513f814528c4df39cf4f48bc9d46e5a6b48ad4d2d1d70
    name: adaptive
    type: application
    urls:
    - https://raw.githubusercontent.com/adaptive-ml/adaptive-helm-chart/main/charts/adaptive-0.0.1.tgz
    version: 0.0.1
generated: "2024-12-13T15:38:03.852062+01:00"
