apiVersion: v2
name: monitoring
description: A Helm chart for installing dev monitoring stack for adaptive engine
kubeVersion: ">=1.26.0-0"

type: application

version: 0.2.0

maintainers:
  - name: adaptive-ml
    url: https://www.adaptive-ml.com/
