apiVersion: 1
datasources:
  - name: Loki
    type: loki 
    access: proxy
    url: http://loki:3100
    jsonData:
      httpMethod: POST
  - name: Prometheus
    type: prometheus 
    access: proxy
    url: http://adaptive-prometheus
    jsonData:
      httpMethod: POST