apiVersion: apps/v1
kind: Deployment
metadata:
  name: flog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flog
  template:
    metadata:
      labels:
        app: flog
      annotations:
        enable-logs-ingest: "true"
    spec:
      containers:
        - name: flog
          image: mingrammer/flog:0.4.3
          args: ["-s", "10s", "-d", "1s", "-l"] # Generate logs every 20s in JSON format
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
