{{- if eq .Values.grafana.enablePersistence false }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.grafana.pvc.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.grafana.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.pvc.size}}
{{- end}}
