apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.service.name }}
  namespace: {{ .Release.Namespace}}
  {{- with .Values.grafana.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.grafana.ports.port }}
      targetPort: {{ .Values.grafana.ports.port }}
      name: 
  {{- with .Values.grafana.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    
