apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: loki
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: pyroscope
      protocol: TCP
      port: 4040
      targetPort: 4040
    - name: otel-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otel-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
