loki: 
  kind: StatefulSet 
  name: loki
  labels:
    app: loki 
  replicas: 1
  serviceAccountName: loki
  container: 
    image: grafana/loki:2.9.11
    port: http-metrics
  terminationGracePeriod: 60
  service:
    name: loki








