## Reference: https://helm.sh/docs/topics/registries/
name: Publish Helm Charts to OCI Registry
on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and Push Adaptive Chart
        run: |
          cd charts
          helm dependency update adaptive
          helm package adaptive
          helm push adaptive-*.tgz oci://ghcr.io/${{ github.repository_owner }}

      - name: Package and Push Monitoring Chart
        run: |
          cd charts
          helm package monitoring
          helm push monitoring-*.tgz oci://ghcr.io/${{ github.repository_owner }}

      - name: Logout from Registry
        if: always()
        run: helm registry logout ghcr.io